spring:
  config:
    activate:
      on-profile: dev
  flyway:
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      show-details: when_authorized

sfl:
  security:
    enabled: ${SFL_SECURITY_ENABLED:true}
