spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SFL_DB_URL}
    username: ${SFL_DB_USERNAME}
    password: ${SFL_DB_PASSWORD}
  flyway:
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      show-details: never

sfl:
  security:
    enabled: ${SFL_SECURITY_ENABLED:true}
