spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${SFL_TEST_DB_URL:jdbc:postgresql://localhost:5434/sfl_java_test}
    username: ${SFL_TEST_DB_USERNAME:postgres}
    password: ${SFL_TEST_DB_PASSWORD:}
  flyway:
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate

sfl:
  security:
    enabled: false
