package gh.edu.clet.sfl.common.security;

public enum SflPermission {
    FACILITIES_WORK_ORDER_CREATE,
    FACILITIES_WORK_ORDER_ASSIGN,
    FACILITIES_WORK_ORDER_CLOSE,
    FACILITIES_WORK_ORDER_READ,
    FACILITIES_READINESS_MANAGE,
    FACILITIES_MASTER_DATA_MANAGE,
    ASSET_REFERENCE_MANAGE,
    ASSET_REFERENCE_READ,
    AUDIT_READ,
    INTEGRATION_HEALTH_READ
}